### ISSUE TITLE
failed opening in Oculus1 

### ISSUE THREAD

**Issue by Rotems1234** [yaoling1997/OpenRDW#2]
Hi,
I have been trying to use your RDW tool and am struggling to open the basic scene in oculus1.

I am trying to use the RDW toolkit in a basic VR project I am working on.

if possible, could you give me your email address for questions related to your work?
I am available at shtl@post.bgu.ac.il
Rotem

**Comment by yaoling1997** [comment]
Thanks for your comments, currently we only tested OpenRDW on PC (windows10) and Vive HMD, you can find more information about OpenRDW in the [wiki page](https://github.com/yaoling1997/OpenRDW/wiki/HMD-Setting). OpenRDW uses the [SteamVR Plugin](https://assetstore.unity.com/packages/tools/integration/steamvr-plugin-32647) for VR support, maybe you can find out how to use this plugin to support oculus devices.

**Comment by yaoling1997** [comment]
.
